#ifndef OFFSETS_H
#define OFFSETS_H

#include <windows.h>

#define OFFSET_GAME_MANAGER 0x5018778
#define OFFSET_GAME_STAUS_MANAGER 0x5017748
#define OFFSET_GAME_MANAGER_ENTITY_COUNT 0x1D0 
#define OFFSET_GAME_MANAGER_ENTITY_LIST2 0x1D8 
#define OFFSET_NETWORK_MANAGER 0x5007fc8

#define OFFSET_ENTITY_COMPONENT 0x28 // Cav ESP 1 
#define OFFSET_ENTITY_COMPONENT_LIST 0xD8 // Cav ESP 2 
#define OFFSET_ENTITY_COMPONENT_HEALTH 0x140 

#define OFFSET_SPOOF_SPECTATE 0x5007FB8
#define OFFSET_SPOOF_SPECTATE_ENABLE 0x5D 

#define OFFSET_ENVIRONMENT_AREA 0x5C71318 // brilho 
#define OFFSET_ENVIRONMENT_AREA_GLOW 0xB8 
#define OFFSET_ENVIRONMENT_AREA_GLOW_ON 0x114 // 0x11C; // 999.f 
#define OFFSET_ENVIRONMENT_AREA_START_DISTANCE 0x130 // 0x138; // 1.0f 
#define OFFSET_ENVIRONMENT_AREA_RELIEF 0x138 // 0x140; // 2.0f


#define OFFSET_STATUS_MANAGER 0x5005928
#define OFFSET_STATUS_MANAGER_CONTAINER 0x370 // 
#define OFFSET_STATUS_MANAGER_LOCALENTITY 0x28 // 

#define ENTITY_MARKER_VT_OFFSET 0x37791e8
#define ENTITY_MARKER_ENABLED_OFFSET 0x530

#define OFFSET_ENTITY_PAWN 0x50
#define OFFSET_ENTITY_PAWN_POSITION 0x6A0

#define OFFSET_ENTITY_REPLICATION 0xC8 
#define OFFSET_ENTITY_REPLICATION_TEAM 0x190 
#define OFFSET_ENTITY_REPLICATION_NAME 0x1C0 

#define OFFSET_NET_MANAGER 0x4E96FB8

#define OFFSET_CAMERA_MANAGER 0x5007FC0 
#define OFFSET_CAMERA_ENGINELINK 0x120
#define OFFSET_CAMERA_ENGINE 0x1C8 
#define OFFSET_CAMERA_ENGINE_CAMERA 0x08

#define OFFSET_CAMERA_RIGHT 0xD0
#define OFFSET_CAMERA_UP 0xE0 
#define OFFSET_CAMERA_FORWARD 0xF0 
#define OFFSET_CAMERA_TRANSLATION 0x100 
#define OFFSET_CAMERA_FOVX 0x110 
#define OFFSET_CAMERA_FOVY 0x124 
#define OFFSET_TRIGGER_BOT 0x4FF0F30

#define OFFSET_SCREEN_MANAGER 0x4E95A00 // não atualizado 
#define OFFSET_SCREEN_WIDTH 0x10 
#define OFFSET_SCREEN_HEIGHT 0x14 
#define OFFSET_TRIGGERBOT                     0x03E15628
#define OFFSET_TRIGGERBOT1                     0xD4
#define OFFSET_TRIGGERBOT2                       0x60 
#define OFFSET_TRIGGERBOT3                       0x0 
#define OFFSET_TRIGGERBOT4                   0x158  
#define OFFSET_TRIGGERBOT5                     0x40
#define OFFSET_LOCAL                         0x05C70860 //para o time aliado local = valor 3  
#define OFFSET_LOCAL1                         0x88
#define OFFSET_LOCAL2                        0x38
#define OFFSET_LOCAL3                         0x68
#define OFFSET_LOCAL4                         0x20   //para o time inimigo = valor 4

#ifdef _AMD64_
#define _PTR_MAX_VALUE ( 0x000F000000000000 )
#else 
#define _PTR_MAX_VALUE ( 0xFFE00000 )
#endif

inline bool _VALID( UINT_PTR Ptr )
{
	return ( Ptr >= 0x10000 ) && ( Ptr < _PTR_MAX_VALUE );
}

#endif